DJ_Foundations/DJ_Foundations/urls.py
from django.contrib import admin
from django.urls import path
from charity.views import *
from django.conf import settings
from django.conf.urls.static import static
from charity.views import donor_login
from DJ_Foundations.settings import MEDIA_URL



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('all_logins', all_logins,name='all_logins'),
    path('donor_login', donor_login,name='donor_login'),
    path('distributor_login', distributor_login,name='distributor_login'),
    path('admin_login', admin_login,name='admin_login'),
    path('donor_reg', donor_reg,name='donor_reg'),
    path('donor_home', donor_home,name='donor_home'),
    path('admin_home', admin_home,name='admin_home'),
    path('donor_base', donor_base,name='donor_base'),
    path('admin_base', donor_base,name='admin_base'),
    path('logout/', Logout,name='logout'),
    path('donate_now', donate_now,name='donate_now'),
    path('donate_history', donation_history,name='donation_history'),




]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DJ_Foundations/charity/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Donor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=15, null= True)
    address = models.CharField(max_length=300, null = True)
    userpic = models.FileField(null=True)
    regdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username

class Distributor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=15, null= True)
    address = models.CharField(max_length=300, null = True)
    userpic = models.FileField(null=True)
    idpic = models.FileField(null=True)
    aboutme = models.CharField(max_length = 300, null=True)
    status = models.CharField(max_length=20, null= True)
    regdate = models.DateTimeField(auto_now_add=True)
    adminremarks = models.CharField(max_length=200, null= True)
    updationdate = models.DateField(null= True)
 
    def __str__(self):
        return self.user.username



class DonationArea(models.Model):
    location = models.CharField(max_length=100, null= True)
    discription = models.CharField(max_length=300, null = True)
    creationdate = models.DateField(auto_now_add=True)
 
    def __str__(self):
        return self.areaname 
    
class Donation(models.Model):
    donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    donationname = models.CharField(max_length=100, null= True)
    donationpic = models.FileField(null=True)
    collectionlocation = models.CharField(max_length=300, null = True)
    description = models.CharField(max_length=300, null = True)
    status = models.CharField(max_length=50, null= True)
    donationdate = models.DateField(auto_now_add=True)
    adminremarks = models.CharField(max_length=200, null= True)
    distributor = models.ForeignKey(Distributor, on_delete=models.CASCADE)
    donationarea = models.ForeignKey(DonationArea, on_delete=models.CASCADE)
    distributorremarks = models.CharField(max_length=200, null= True)
    updationdate = models.DateField(null=True)
 
    def __str__(self):
        return self.id
    
class Gallery(models.Model):
    donotion = models.ForeignKey(Donation, on_delete=models.CASCADE)
    delivarynpic = models.FileField(null=True)
    creationdate = models.DateField(auto_now_add=True)

    
 
    def __str__(self):
        return self.id

DJ_Foundations/charity/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login , logout
from .models import *

# Create your views here.
def index(request):
    return render(request, 'index.html')
def all_logins(request):
    return render(request, 'all_logins.html' )

#   for donor login
def donor_login(request):
    if request.method == "POST":
        email = request.POST.get('emailid')
        pwd = request.POST.get('pwd')
        user = authenticate(username=email,password=pwd)
        if user:
            login(request, user)
            error = 'no'

        else:
            error = 'yes'
    return render(request, 'donor_login.html', locals())
    
def distributor_login(request):
    return render(request, 'distributor_login.html')

#   for admin login

def admin_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        pwd = request.POST.get('pwd')
        user = authenticate(username=username,password=pwd)
        try:
             if user.is_staff:
                login(request, user)
                error = 'no'

             else:
                error = 'yes'
        except:
            error = "yes"   
    return render(request, 'admin_login.html', locals())

#   for signup

def donor_reg(request):
    error = ""

    if request.method == "POST":
        fn = request.POST.get('firstname')
        ln = request.POST.get('lastname')
        em = request.POST.get('email')
        contact = request.POST.get('contact')
        pwd = request.POST.get('pwd')
        userpc = request.FILES.get('userpic')
        address = request.POST.get('address')

        try:
            user = User.objects.create_user(first_name=fn, last_name=ln, username=em, password=pwd)
            Donor.objects.create(user=user, contact=contact, userpic=userpc, address=address)

            error = 'no'
        except Exception as e:
            error = 'yes'
            print(e)
    return render(request, 'donor_reg.html', locals())

# donor Homepage
def donor_home(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    return render(request, 'donor_home.html')

# admin Homepage
def admin_home(request):
    if not request.user.is_authenticated:
        return redirect('admin_login')
    return render(request, 'admin_home.html')
    

def donor_base(request):
    return render(request, 'donor_base.html')

def admin_base(request):
    return render(request, 'admin_base.html')




def Logout(request):
    logout(request)
    return redirect('index')
    
def donate_now(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    user = request.user
    donor = Donor.objects.get(user=user)
    if request.method == "POST":
       donationname = request.POST.get('donationname')
       donationpic = request.FILES.get('donationpic')
       collectionlocation = request.POST.get('collectionlocation')
       description = request.POST.get('description')
       
       try:
        #    distributor = Distributor.objects.get(id=1)
           Donation.objects.create(donor=donor, donationname=donationname,donationpic = donationpic, collectionlocation=collectionlocation, description= description, status = "pending")
           error = "no"
       except Exception as e:
           print("Error:", e)
           error = "yes"
        #    print(connection.queries)
    return render(request, 'donate_now.html', locals())

def donation_history(request):
    if not request.user.is_authenticated:
        return redirect('donor_login')
    user = request.user
    donor = Donor.objects.get(user = user)
    donation = Donation.objects.filter(donor=donor)
    
    return render(request, 'donation_history.html',{'donation':donation})

DJ_Foundations/charity/templates/admin_base.html
{% load static %}

<html>

<head>
    <title>AJ Charity Foundation</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" crossorigin="anonymous">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <script src="{% static 'js/myjs.js' %}"></script>
</head>

<body>
    <!-- vertical navbar start -->
    <div class="vertical-nav bg-white" id="sidebar">
        <div class="py-4 px-3 mb-1 bg-light">
            <!--align media objects (like images or videos) together with content
         To create a flexbox container and to transform direct children into flex items, -->
            <p class="text-center font-weight-bold text-uppercase px-3 small dashboard-text">AJ Charity Foundation
            </p>

            <div class="media d-flex align-items-center">
                <img src="#" width="80" height="80" class="mr-3 rounded-circle img-thumbnail shadow-sm">

                <div class="media-body">
                    <h4 class="mb-0">Admin</h4>
                    <p class="text-muted mb-0">{{request.user.email}}</p>
                </div>
            </div>
        </div>

        <!-- flex-column to display the flex items vertically (on topof each other) -->
        <ul class="nav flex-column bg-white">
            <li class="nav-item">
                <a href="{% url 'admin_home' %}" class="nav-link text-dark bg-light">
                    <i class="fas fa-tachometer-alt fa-fw mr-3 text-primary"></i>
                    Dashboard
                </a>
            </li>


            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>Services
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Add Services</a>
                    <a class="dropdown-item" href="">Manage Services</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>Contact Us Queries
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Unread Queries</a>
                    <a class="dropdown-item" href="">Read Queries</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>Booking
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Add Services</a>
                    <a class="dropdown-item" href="">Manage Services</a>
                </div>
            </li>

            <li class="nav-item">
                <a href="" class="nav-link text-dark bg-light">
                    <i class="fas fa-cog mr-3 text-primary fa-fw"></i>
                    Change Password
                </a>
            </li>




        </ul>
    </div>
    <!-- vertical navbar end-->

    <!-- page content holder -->
    <div class="page-content p-4" id="content">
        <a href="{% url 'logout' %}" title="logout" class="float-right text-white"><i
                class="fas fa-sign-out-alt"></i></a>

        <!--toggle btn -->
        <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill">
            <i class="fas fa-bars mr-2">
                <small class="text-uppercase font-weight-bold">Toggle</small>

            </i>
        </button>

        {% block main%}

        {% endblock %}
    </div>
    <!-- end page content holder -->
</body>

</html>

DJ_Foundations/charity/templates/admin_home.html
{% extends 'admin_base.html' %}

{% block main %}

{% endblock %}

DJ_Foundations/charity/templates/admin_login.html
{% load static %}
<html>

<head>
    <style>
        body#login {
            background-image: url("{% static 'images/bg.jpeg' %}");
            /* Add other background properties as needed */
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha384-r5lZgphvS/cxzRTIAGeVcZVzN1pa2ziSLfzZ2QF7AdJ7c+e4l8im3e5E9PloWMMs" crossorigin="anonymous">
</head>

<body id="login">
    {% include 'navigation.html' %}
    <hr class="mt-0">

    <div class="row">
        <div class="col-lg-5 m-auto">
            <div class="card mt-5 bg-dark">
                <div class="card-title text-center mt-3">
                    <img src="{% static 'images/useravatar.png' %}" width="150" height="150">
                    <h2 class="text-white">Admin login</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-user fa-2x"></i>
                                </span>
                            </div>
                            <input type="text" name="username" class="form-control" placeholder="user name">
                            <!-- Use Bootstrap's form-control class for width adjustment -->
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-lock fa-2x"></i>
                                </span>
                            </div>
                            <input type="password" name="pwd" class="form-control" placeholder="password">
                            <!-- Use Bootstrap's form-control class for width adjustment -->
                        </div>
                        <input type="submit" value="login" class="btn btn-success py-2">
                        <a href="{% url 'index' %}" class="float-right text-white mt-2">Back to Home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
{% if error == "no" %}
<script>
    alert('Logged In Successful');
    window.location = ('{% url "admin_home" %}');
</script>
{% endif %}

{% if error == "yes" %}
<script>
    alert('Invalid Login Credentials, Try again....');
</script>
{% endif %}

</html>

DJ_Foundations/charity/templates/all_logins.html
{% load static %}
<html>

<head>
</head>

<body>
    {% include 'navigation.html' %}
    <hr class="mt-0">

    <div class="container mt-5 p-3">
        <h2 class="text-center">Login As a</h2>
        <div class="row">
            <div class="col-lg-4 mb-3">
                <div class="card" style="width: 300px;">
                    <img src="{% static 'images/donor.jpg' %}" alt="" class="card-img-top"
                        style="width: 100%; height:200px;">
                    <div class="card-body">
                        <h4 class="card-title text-center">Donor</h4>
                        <p class="card-text text-center">Some example text.</p>
                        <a href="{% url 'donor_login' %}" class="btn btn-primary text-center">Go To Donor Login</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-3">
                <div class="card" style="width: 300px;">
                    <img src="{% static 'images/donor.jpg' %}" alt="" class="card-img-top"
                        style="width: 100%; height:200px;">
                    <div class="card-body">
                        <h4 class="card-title text-center">Distributor</h4>
                        <p class="card-text text-center">Some example text.</p>
                        <a href="{% url 'distributor_login' %}" class="btn btn-primary text-center">Go To Distributor
                            Login</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 mb-3">
                <div class="card" style="width: 300px;">
                    <img src="{% static 'images/donor.jpg' %}" alt="" class="card-img-top"
                        style="width: 100%; height:200px;">
                    <div class="card-body">
                        <h4 class="card-title text-center">Admin</h4>
                        <p class="card-text text-center">Some example text.</p>
                        <a href="{% url 'admin_login' %}" class="btn btn-primary text-center">Go To Admin Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

DJ_Foundations/charity/templates/distributor_login.html
{% load static %}
<html>

<head>
    <style>
        body#login {
            background-image: url("{% static 'images/bg.jpeg' %}");
            /* Add other background properties as needed */
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha384-r5lZgphvS/cxzRTIAGeVcZVzN1pa2ziSLfzZ2QF7AdJ7c+e4l8im3e5E9PloWMMs" crossorigin="anonymous">
</head>

<body id="login">
    {% include 'navigation.html' %}
    <hr class="mt-0">

    <div class="row">
        <div class="col-lg-5 m-auto">
            <div class="card mt-5 bg-dark">
                <div class="card-title text-center mt-3">
                    <img src="{% static 'images/useravatar.png' %}" width="150" height="150">
                    <h2 class="text-white">Distributor login</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-user fa-2x"></i>
                                </span>
                            </div>
                            <input type="email" name="emailid" class="form-control" placeholder="email id">
                            <!-- Use Bootstrap's form-control class for width adjustment -->
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">
                                    <i class="fa fa-lock fa-2x"></i>
                                </span>
                            </div>
                            <input type="password" name="pwd" class="form-control" placeholder="password">
                            <!-- Use Bootstrap's form-control class for width adjustment -->
                        </div>
                        <input type="submit" value="login" class="btn btn-success py-2">
                        <a href="{% url 'index' %}" class="float-right text-white mt-2">Back to Home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

DJ_Foundations/charity/templates/donate_now.html
{% extends 'donor_base.html' %}


{% block main %}
<div class="card shadow mt-4">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom :2px solid orange">Donate Now</h5>

        <div class="container-fluid">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Donation Name<span style="color :red">(Note:If u select other,plz mention detail in
                                    description)</span></label>
                            <select name="donationname" class="form-control">
                                <option value="Money Donation">
                                    Money Donation
                                </option>
                                <option value="Food Donation">
                                    Food Donation
                                </option>
                                <option value="Cloth Donation">
                                    Cloth Donation
                                </option>
                                <option value="Footwear Donation">
                                    Footwear Donation
                                </option>
                                <option value="Books Donation">
                                    Books Donation
                                </option>
                                <option value="Furniture Donation">
                                    Furniture Donation
                                </option>
                                <option value="Vessel Donation">
                                    Vessel Donation
                                </option>
                                <option value="Toy Donation">
                                    Toy Donation
                                </option>
                                <option value="Other Donation">
                                    Others
                                </option>
                            </select>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Donation Image</label>
                            <input type="file" name="donationpic" class="form-control" required>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Donation Collection Address</label>
                            <textarea name="ccollectionlocation" class="form-control" placeholder="Enter Full Address"
                                required></textarea>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Description(Special Note)</label>
                            <textarea name="description" class="form-control" placeholder="Special note for donation"
                                required></textarea>
                        </div>
                    </div>


                </div>

                <input type="submit" value="Donate Happiness" class="btn btn-danger px-3 m-2">
            </form>
        </div>
    </div>
</div>
{% if error == "no" %}
<script>
    alert('Donation collection has been send. We will contact you soon');
    window.location = ('{% url "donation_history" %}');   
</script>
{% endif %}

{% if error == "yes" %}
<script>
    alert('Somethong went wrong. Please try again');   
</script>
{% endif %}
{% endblock %}

DJ_Foundations/charity/templates/donation_history.html
{% extends 'donor_base.html' %}

{% block main %}

<div class="card shadow mt-4">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange;">Donation History</h5>

        <div class="container-fluid">

            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th>S.NO</th>
                        <th>Bonation Name</th>
                        <th>Donation Date</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in donation %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ i.donationname }}</td>
                        <td>{{ i.donationdate }}</td>
                        <td>{{ i.status }}</td>
                        <td><a href="#" class="text-primary">View Details</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
</div>
{% endblock %}

DJ_Foundations/charity/templates/donor_base.html
{% load static %}

<html>

<head>
    <title>AJ Charity Foundation</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" crossorigin="anonymous">

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <script src="{% static 'js/myjs.js' %}"></script>
</head>

<body>
    <!-- vertical navbar start -->
    <div class="vertical-nav bg-white" id="sidebar">
        <div class="py-4 px-3 mb-1 bg-light">
            <!--align media objects (like images or videos) together with content
         To create a flexbox container and to transform direct children into flex items, -->
            <p class="text-center font-weight-bold text-uppercase px-3 small dashboard-text">AJ Charity Foundation
            </p>

            <div class="media d-flex align-items-center">
                <img src="{{request.user.donor_set.all.0.userpic.url}}" width="80" height="80"
                    class="mr-3 rounded-circle img-thumbnail shadow-sm">

                <div class="media-body">
                    <h4 class="mb-0">Donor</h4>
                    <p class="text-muted mb-0">{{request.user.username}}</p>
                </div>
            </div>
        </div>

        <!-- flex-column to display the flex items vertically (on topof each other) -->
        <ul class="nav flex-column bg-white">
            <li class="nav-item">
                <a href="{% url 'donor_home' %}" class="nav-link text-dark bg-light">
                    <i class="fas fa-tachometer-alt fa-fw mr-3 text-primary"></i>
                    Dashboard
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'donate_now' %}" class="nav-link text-dark bg-light">
                    <i class="fas fa-tachometer-alt fa-fw mr-3 text-primary"></i>
                    Donate Now
                </a>
            </li>


            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>Services
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Add Services</a>
                    <a class="dropdown-item" href="">Manage Services</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>Contact Us Queries
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Unread Queries</a>
                    <a class="dropdown-item" href="">Read Queries</a>
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark bg-light" href="#" id="navbardrop">
                    <i class="fas fa-chart-bar mr-3 text-primary fa-fw"></i>Booking
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="">Add Services</a>
                    <a class="dropdown-item" href="">Manage Services</a>
                </div>
            </li>

            <li class="nav-item">
                <a href="" class="nav-link text-dark bg-light">
                    <i class="fas fa-cog mr-3 text-primary fa-fw"></i>
                    Change Password
                </a>
            </li>




        </ul>
    </div>
    <!-- vertical navbar end-->

    <!-- page content holder -->
    <div class="page-content p-4" id="content">
        <a href="{% url 'logout' %}" title="logout" class="float-right text-white"><i
                class="fas fa-sign-out-alt"></i></a>

        <!--toggle btn -->
        <button id="sidebarCollapse" type="button" class="btn btn-light bg-white rounded-pill">
            <i class="fas fa-bars mr-2">
                <small class="text-uppercase font-weight-bold">Toggle</small>

            </i>
        </button>

        {% block main%}

        {% endblock %}
    </div>
    <!-- end page content holder -->
</body>

</html>

DJ_Foundations/charity/templates/donor_home.html
{% extends 'donor_base.html' %}

{% block main %}

{% endblock %}